before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: obDMHDEncP/+J+rDGTJdZ8ctBV2xsPI4RPpQ0skige6atQVs+MJPln7r3VnRyR3+DLcANg94WCEF8COQpyTH7fahWl4Xn4tB2HKSAZJKwi0607Ihja8VzgIbm2ZNtn+LAnKnvzwu6GjzKQcgY8d7Cg3FxkU6XTKvC1L44W9rnahSFrXtGk0CJ4MlEPZdTr/fwk4Ad+TEZgIGt/laTpYia+IUn2x1R+080VO3ztfQQafWEBxA/CPjJdlTvZSFqZ5FzeQ6PmVAGg/Kf7kER7vpIPw9pRoCzWgvTzoPX5BPGJyRvNmNaHLyKzAZ9VGF8bZx0phyZPyPWzq7fCCCv8nEF+4aUYOxcn29zb4gRpbHDB8BH+koB6er23R5bcqKMzBMtsVYxHCc7kf3JXd87KMYCk+3Cdl7fnNBibYFPczln1dhKDegR/DH6C0HVks6rvK56KllsZD0uSDAnhFMcB8OtsjTgqOx1Wv+YCzatKFL+IMh9iHSJnGQL4fZtG0LMKMSgRmvBd2vkYjrvlk+ona9DlqQLK3FyfxmYKBnV8aTnQBotrLPov8zJt9s23j5qmSJWwpJrukRifQKMubTJk4aLCLd9E3JJGPrE8mKyWJGBGLSk5un2YUlnwi51S2TuvrihLLJzhkrNOj3a572u95drXz6giUY5HG1OBsueCA/vCs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
